### PR TITLE
Tweaks to get Summa to compile on *buntu machines

### PR DESCRIPTION
**Pull request by naught101**
fixes #77

### CODE REVIEW

**Comment by naught101** [comment]
Also, on a separate note, the test cases tar file at https://ral.ucar.edu/projects/summa isn't a link - I can't download it.

**Comment by bartnijssen** [comment]
That's correct - the web person wasn't available yesterday and Martyn is out today (hence the soft release).

**Comment by bartnijssen** [comment]
@naught101 : It's not ideal because we have to go through another party for the SUMMA site at UCAR. For now you can download the test data from: https://www.dropbox.com/s/qe3vgqoalf7adn2/summaTestCases.tar.gz?dl=0

Note that I will delete this once the link on the SUMMA page works.

**Comment by naught101** [comment]
Great, thanks, I'll see if I can get it working.

**Pull request merged**
